"""added price data type

Revision ID: 157dd812f474
Revises: f672aa6c4354
Create Date: 2024-03-14 13:02:08.828983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157dd812f474'
down_revision = 'f672aa6c4354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
