"""added contact in user

Revision ID: f672aa6c4354
Revises: 14c28029a4d6
Create Date: 2024-03-14 11:34:49.211566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f672aa6c4354'
down_revision = '14c28029a4d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.drop_column('contact')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(), nullable=True))
        batch_op.alter_column('registration_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('registration_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.drop_column('contact')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
